# Generated by Django 2.0.9 on 2018-11-07 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0002_auto_20181107_0042'),
        ('minutas', '0002_meeting_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='date',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='minute',
            name='date',
        ),
        migrations.AddField(
            model_name='minute',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='refuseminute',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='minute',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='refuseminute',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('userprofile', 'minute')},
        ),
        migrations.RemoveField(
            model_name='refuseminute',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='refuseminute',
            unique_together={('userprofile', 'minute')},
        ),
    ]
