# Generated by Django 2.1.2 on 2018-11-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0003_auto_20181107_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='document',
            field=models.FileField(default=None, upload_to='Minuta'),
        ),
    ]
