# Generated by Django 2.1.2 on 2018-11-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0004_minute_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Minuta'),
        ),
    ]
