# Generated by Django 2.1.2 on 2018-11-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0005_auto_20181113_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Minuta'),
        ),
    ]
