# Generated by Django 2.1.2 on 2018-11-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0006_auto_20181113_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='document',
            field=models.FileField(null=True, upload_to='Minuta'),
        ),
    ]
