# Generated by Django 2.1.2 on 2018-11-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0008_auto_20181113_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='document',
            field=models.FileField(default='0', upload_to='Minuta'),
        ),
    ]
