# Generated by Django 2.1.1 on 2018-11-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0010_auto_20181113_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Minuta/'),
        ),
    ]
