# Generated by Django 2.1.1 on 2018-11-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0011_auto_20181114_1812'),
        ('minutas', '0011_auto_20181114_1509'),
    ]

    operations = [
    ]
