# Generated by Django 2.1.1 on 2018-09-15 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin Nombre', max_length=200)),
                ('api_pk', models.CharField(default=None, max_length=4)),
                ('user_type', models.CharField(choices=[('AL', 'Alumno'), ('DO', 'Docente'), ('AD', 'Administrador')], default='AL', max_length=2)),
                ('carreer', models.CharField(default='Sin Carrera', max_length=200)),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
