# Generated by Django 2.1.2 on 2018-11-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0003_auto_20181107_2202'),
        ('retro_auth', '0003_userprofile_umbral'),
    ]

    operations = [
    ]
