# Generated by Django 2.0.9 on 2018-11-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0003_userprofile_umbral'),
        ('retro_auth', '0003_auto_20181107_2202'),
    ]

    operations = [
    ]
