# Generated by Django 2.1.1 on 2018-11-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0003_auto_20181107_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dcareer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_sacademic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
