# Generated by Django 2.1.1 on 2018-09-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0003_auto_20180924_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='api_pk',
            field=models.CharField(default='NoPK', max_length=4),
        ),
    ]
