# Generated by Django 2.0.9 on 2018-11-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0004_merge_20181113_0307'),
        ('retro_auth', '0004_merge_20181113_0200'),
        ('retro_auth', '0004_merge_20181113_1945'),
    ]

    operations = [
    ]
