# Generated by Django 2.1.1 on 2018-11-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0005_merge_20181114_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dcareer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sacademic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
