# Generated by Django 2.1.2 on 2018-11-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0005_merge_20181114_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dcareer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_sacademic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
