# Generated by Django 2.1.1 on 2018-11-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0004_auto_20181113_2251'),
        ('retro_auth', '0005_merge_20181114_0123'),
    ]

    operations = [
    ]
