# Generated by Django 2.1.1 on 2018-11-16 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0006_merge_20181114_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='umbral',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)]),
        ),
    ]
