# Generated by Django 2.1.1 on 2018-11-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0006_auto_20181114_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dcareer',
            new_name='is_dcareer',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='sacademic',
            new_name='is_sacademic',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='teacher',
            new_name='is_teacher',
        ),
    ]
