# Generated by Django 2.1.1 on 2018-11-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0007_auto_20181114_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
