# Generated by Django 2.1.1 on 2018-09-24 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='retro.Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('AY', 'Ayudantia'), ('CA', 'Catedra')], default='CA', max_length=2),
        ),
    ]
