# Generated by Django 2.0.9 on 2018-11-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersubjectsection',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retro.Section'),
        ),
    ]
