# Generated by Django 2.1.1 on 2018-09-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0002_auto_20180923_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='schedule',
            field=models.CharField(default='Sin Horario', max_length=100),
        ),
    ]
