# Generated by Django 2.1.1 on 2018-11-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0003_auto_20181107_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarchive',
            name='document',
            field=models.FileField(default=None, upload_to='Foro/Comment/%Y/%m/%d/'),
        ),
    ]
