# Generated by Django 2.1.1 on 2018-09-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0003_section_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='api_pk',
            field=models.CharField(default='NoPK', max_length=4),
        ),
    ]
