# Generated by Django 2.1.3 on 2018-11-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_post_seguir'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfollower',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
