# Generated by Django 2.1.2 on 2018-11-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_auto_20181111_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
