# Generated by Django 2.1.1 on 2018-09-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_auto_20180924_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='nrc',
            field=models.CharField(default='NoNRC', max_length=6),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default='No Code', max_length=40),
        ),
        migrations.AlterField(
            model_name='section',
            name='api_pk',
            field=models.CharField(default='NoPK', max_length=4),
        ),
    ]
