# Generated by Django 2.1.3 on 2018-11-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0005_postfollower_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadfollower',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
