# Generated by Django 2.0.9 on 2018-11-07 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('retro_auth', '0002_auto_20181107_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alertas.AnswerReport')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_audit', to='retro_auth.UserProfile')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_audit', to='retro_auth.UserProfile')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_audit', to='retro_auth.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='foroaudit',
            unique_together={('director', 'student', 'teacher')},
        ),
    ]
