# Generated by Django 2.0.9 on 2018-11-07 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0002_auto_20181107_0042'),
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinutesAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_audit_minute', to='retro_auth.UserProfile')),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofile_audit_minute', to='retro_auth.UserProfile')),
            ],
        ),
        migrations.AlterField(
            model_name='foroaudit',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_audit_foro', to='retro_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='foroaudit',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_audit_foro', to='retro_auth.UserProfile'),
        ),
        migrations.AlterField(
            model_name='foroaudit',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_audit_foro', to='retro_auth.UserProfile'),
        ),
    ]
