# Generated by Django 2.0.9 on 2018-11-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foroaudit',
            name='seccion',
        ),
    ]
