# Generated by Django 2.0.4 on 2018-11-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retro', '0001_initial'),
        ('auditorias', '0001_initial'),
        ('retro_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foroaudit',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retro.Section'),
        ),
        migrations.AddField(
            model_name='foroaudit',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_audit_foro', to='retro_auth.UserProfile'),
        ),
        migrations.AddField(
            model_name='foroaudit',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_audit_foro', to='retro_auth.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='foroaudit',
            unique_together={('director', 'student', 'teacher')},
        ),
    ]
