# Generated by Django 2.1.2 on 2018-11-13 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0003_auto_20181107_1343'),
        ('auditorias', '0002_auto_20181107_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='foroaudit',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_audit_foro', to='retro.Section'),
        ),
    ]
