# Generated by Django 2.1.2 on 2018-11-13 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0003_foroaudit_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foroaudit',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retro.Section'),
        ),
    ]
