# Generated by Django 2.1.2 on 2018-11-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0005_auto_20181113_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foroaudit',
            old_name='curso',
            new_name='seccion',
        ),
    ]
