# Generated by Django 2.0.9 on 2018-11-17 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minutas', '0001_initial'),
        ('retro', '0001_initial'),
        ('retro_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Post')),
                ('student_answerd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_answer', to='retro_auth.UserProfile')),
                ('student_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_question', to='retro_auth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AlertMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.Minute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro_auth.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerReportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alertas.AnswerReport')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report', to='retro_auth.UserProfile')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_report', to='retro_auth.UserProfile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answerreportuser',
            unique_together={('report', 'student', 'teacher')},
        ),
    ]
