# Generated by Django 2.1.3 on 2018-11-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0002_auto_20181107_0042'),
        ('retro', '0003_auto_20181107_1343'),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Post')),
                ('user_ans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_answer', to='retro_auth.UserProfile')),
                ('user_ask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_question', to='retro_auth.UserProfile')),
            ],
        ),
    ]
