# Generated by Django 2.0.4 on 2018-11-16 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retro', '0001_initial'),
        ('alertas', '0001_initial'),
        ('retro_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Post'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_answer', to='retro_auth.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='answerreportuser',
            unique_together={('report', 'student', 'teacher')},
        ),
    ]
