# Generated by Django 2.0.9 on 2018-11-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0001_initial'),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerreportuser',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_report', to='retro_auth.UserProfile'),
        ),
    ]
