# Generated by Django 2.0.9 on 2018-11-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_answerreportuser_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerreportuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
