# Generated by Django 2.1.3 on 2018-11-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
