# Generated by Django 2.1.1 on 2018-11-16 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0011_auto_20181114_1812'),
        ('retro_auth', '0006_merge_20181114_2221'),
        ('alertas', '0002_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.Minute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro_auth.UserProfile')),
            ],
        ),
    ]
