# Generated by Django 2.0.9 on 2018-11-12 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alerta'),
        ('alertas', '0002_notification'),
    ]

    operations = [
    ]
