# Generated by Django 2.1.3 on 2018-11-17 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_auto_20181111_2345'),
        ('retro_auth', '0005_merge_20181114_0123'),
        ('alertas', '0002_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Post')),
                ('user_ans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_answer', to='retro_auth.UserProfile')),
                ('user_ask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_question', to='retro_auth.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='post',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='student',
        ),
        migrations.DeleteModel(
            name='Alerta',
        ),
    ]
