# Generated by Django 2.1.1 on 2018-11-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retro_auth', '0005_merge_20181114_0123'),
        ('alertas', '0002_alerta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerta',
            old_name='student',
            new_name='student_answerd',
        ),
        migrations.AddField(
            model_name='alerta',
            name='student_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_report_question', to='retro_auth.UserProfile'),
        ),
    ]
