# Generated by Django 2.1.1 on 2018-11-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutas', '0011_auto_20181114_1509'),
        ('retro_auth', '0005_merge_20181114_0123'),
        ('alertas', '0003_auto_20181114_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutas.Minute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro_auth.UserProfile')),
            ],
        ),
    ]
