# Generated by Django 2.1.1 on 2018-11-14 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_alertminute'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertminute',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
