# Generated by Django 2.1.1 on 2018-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0005_alertminute_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertminute',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
